apiVersion: tekton.dev/v1beta1 
kind: PipelineRun 
metadata:
  name: create-user-pipelinerun 
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: create-user-pipeline  
  params: 
  - name: namespace-name
    value: toto-namespace
  - name: git-url
    value: https://gitlab.consulting.redhat.com/vbroniko/k8s-createusers-playbook.git 
  - name: user-name
    value: toto
  - name: target-cluster
    value: https://api.cluster-l7c2k.l7c2k.sandbox2467.opentlc.com:6443
  workspaces: 
  - name: shared-mount
    volumeClaimTemplate:
      spec:
        storageClassName: gp3-csi 
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
