apiVersion: v1
kind: Secret
metadata:
  name: auth-gitlab
  annotations:
    tekton.dev/git-0: github.com
    tekton.dev/git-1: gitlab.com
type: kubernetes.io/basic-auth
stringData:
  username: vbroniko
  password: 
